### PR TITLE
fix(next): pass port variable to helm values yaml

### PR DESCRIPTION
**Pull request by MetecanAydin**
[5489](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5489)

- create method setPort for multiple uses
- pass port variable to helm values yaml

### CODE REVIEW

**Review by johnmckenna — CHANGES_REQUESTED** [review]
This probably also needs to do the same to the Dockerfile as well

**Comment by MetecanAydin** [comment]
> This probably also needs to do the same to the Dockerfile as well

image

I believe it already does? Unless you're referring to something else :D

**Comment by johnmckenna** [comment]
> > This probably also needs to do the same to the Dockerfile as well
> 
> image
> 
> I believe it already does? Unless you're referring to something else :D

EXPOSE 3000 needs changed to EXPOSE <

> > This probably also needs to do the same to the Dockerfile as well
> 
> image
> 
> I believe it already does? Unless you're referring to something else :D

EXPOSE 3000 needs changed to EXPOSE  <%= port %>

**Comment by MetecanAydin** [comment]
updated @johnmckenna cheers

**Review by nandorszentpeteri — APPROVED** [review]

**Review by johnmckenna — APPROVED** [review]

**Pull request merged**
