### PR TITLE
fix(rest-client): linting issues and additional info

### PR DESCRIPTION
**Pull request by michaldudek**
- Fix some linting issues.
- Fix some typos.
- Add a note to highlight that if you use the `--directory` option then the project name will change:

Screenshot 2023-02-16 at 17 49 18

It doesn't seem to be very well documented, but in the screenshot above I called my generated library `client`, but decided to put it in the `api` directory, resulting in the library to be generated in `libs/api/client`. I might expect the name to stay as `client`, but it's actually being changed to `api-client` (makes sense, otherwise project name uniqueness could not be ensured). So instead of running `nx test client` I should be running `nx test api-client`.

### CODE REVIEW

**Review by CerdenAmido — APPROVED** [review]

**Comment by Danphillipz** [comment]
Looks like nx cloud had a failed command? "[nx affected --target=lint --base=last-release --parallel=3](https://cloud.nx.app/runs/2AfdE6fbHq)"

**Comment by michaldudek** [comment]
> Looks like nx cloud had a failed command? "[nx affected --target=lint --base=last-release --parallel=3](https://cloud.nx.app/runs/2AfdE6fbHq)"

I can't access this :( Can you copy/paste?

**Comment by Danphillipz** [comment]
> > Looks like nx cloud had a failed command? "[nx affected --target=lint --base=last-release --parallel=3](https://cloud.nx.app/runs/2AfdE6fbHq)"
> 
> I can't access this :( Can you copy/paste?

I can't either, that's from the NX cloud report above, might need @johnmckenna to take a look for us

**Comment by Danphillipz** [comment]
> > Looks like nx cloud had a failed command? "[nx affected --target=lint --base=last-release --parallel=3](https://cloud.nx.app/runs/2AfdE6fbHq)"
> 
> I can't access this :( Can you copy/paste?
This is the error from NX
```
Linting "common-core"...

/home/runner/work/stacks-nx-plugins/stacks-nx-plugins/packages/common/core/src/utils/addCustomTestConfig.ts
  25:2  error  Insert `⏎`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Lint errors found in the listed files.
```

**Pull request merged**
